### PR TITLE
Supporting [String]

### PR DESCRIPTION
**Pull request by JeronimoPaganini**
The right configuration supports only String...
But in the case where I have to prepare SecurityHeadersFactory with a bit different configs, I can just prepare an array variable and increase it without duplicates for e.g.:

``` 
 let cspBuilder = ContentSecurityPolicy()
            .defaultSrc(sources: CSPKeywords.`self`)
            .styleSrc(sources: "https://developer.api.autodesk.com",
                      CSPKeywords.`self`)
            .scriptSrc(sources: "https://developer.api.autodesk.com",
                       CSPKeywords.`self`,
                       "https://www.google.com/recaptcha/",
                       "https://www.gstatic.com/recaptcha/",
                       "https://apis.google.com/js/")
            .frameSrc(sources: "https://www.google.com/recaptcha/",
                      "https://recaptcha.google.com/recaptcha/")
            .imgSrc(sources: CSPKeywords.`self`, "https://lh3.googleusercontent.com/")
        let cspConfig = ContentSecurityPolicyConfiguration(value: cspBuilder)
        securityHeadersFactory = SecurityHeadersFactory().with(contentSecurityPolicy: cspConfig)
and routes group with:
 let dashboardCSPBuilder = ContentSecurityPolicy()
            .defaultSrc(sources: CSPKeywords.`self`)
            .styleSrc(sources: "https://developer.api.autodesk.com",
                      CSPKeywords.`self`,
                      CSPKeywords.unsafeInline)
            .scriptSrc(sources: "https://developer.api.autodesk.com",
                       CSPKeywords.`self`,
                       "https://www.google.com/recaptcha/",
                       "https://www.gstatic.com/recaptcha/",
                       "https://apis.google.com/js/")
            .frameSrc(sources: "https://www.google.com/recaptcha/",
                      "https://recaptcha.google.com/recaptcha/")
            .imgSrc(sources: CSPKeywords.`self`, "https://lh3.googleusercontent.com/")
        
        let dashboardCSPConfig = ContentSecurityPolicyConfiguration(value: dashboardCSPBuilder)
        dashboardSecurityHeadersFactory = SecurityHeadersFactory().with(contentSecurityPolicy: dashboardCSPConfig)
```

the difference only in: `CSPKeywords.unsafeInline` but I have to repeat everything else. 
Using arrays like an arguments we can simple add to variable and re-use/increase it.

### CODE REVIEW

**Comment by 0xTim** [comment]
@JeronimoPaganini thanks for this, I can see the benefits so happy to accept it. Will need tests to cover the new APIs however. You should be able to just copy and paste the existing ones and change them to use the array APIs

**Comment by JeronimoPaganini** [comment]
Ah, sorry for that. 
Will add tests soon :) 
Thanks for the feedback!

**Comment by 0xTim** [comment]
Thanks! This is good to go, I'll merge and ship a release when I'm back off mobile only on Monday

**Review by 0xTim — APPROVED** [review]

**Comment by JeronimoPaganini** [comment]
@0xTim , thanks for the feedback! :)

**Comment by JeronimoPaganini** [comment]
Thank you :)

**Comment by 0xTim** [comment]
This is released in https://github.com/brokenhandsio/VaporSecurityHeaders/releases/tag/3.2.0

**Comment by JeronimoPaganini** [comment]
Yep, I saw :) 
https://github.com/brokenhandsio/VaporSecurityHeaders/pull/24#issuecomment-888330442

**Pull request merged**
